version: '3.8'

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    env_file:
      - ./.env
    volumes:
      - mongodb_data:/data/db
      - ./init:/docker-entrypoint-initdb.d
volumes:
  mongodb_data:  
