# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.1'

    - name: Build
      run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    environment: "Test environment"
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.1'

    - name: 'Create MongoDB env file'
      run: echo "${{ secrets.MONGO_DB_ENV_FILE }}" > "./mongodb/docker/.env"
      
    - name: 'Create Test env file'
      run: echo "${{ secrets.TEST_ENV_FILE }}" > "./test/.env"
      
    - name: Set up database
      run: bash launch_db.sh
      
    - name: Test
      run: bash test.sh
